travis:
  secure:
    BINSTAR_TOKEN: BIErsxnTSDJN5c9SJTQDgoxf6a9/4EsqGq1XOYJ0pqyozST6ggGhhfGsvTGU2PvtLHbvJr9rXbYUyvdkicdhkCqE9iozlW5NVRAPAEXynbdGO0iwUZ+txap3pG1iQ7bSCYhhkCpcZYjW9BpkEdXdIBpLUCRFO/DmPKJRrrlUzPKdix5uBztLrVyv3DISK0YFTHYWzyYCD7ZmAxMpzdPC90N5fZeOWHlTThw0+bLQ6aevmYnk7cZOvbn8Evds8y+Alz8wslcxOpmbQEFvle+lg4GpMynsEZUTlUwhMZuLVkeMtFggT6JjwWX+PBeKzaL7WYuBtADrKHYI/UKzdqk/WMxp8D6Fx+G81puJzZDUjJTBggeozKFYMFcSXxnGOyYKrzgxi2eGUN/9zRjkehk6ZGZOtuofJCRrWEG0v4ImClJP8JSQ/aAJrB0y3u7H2ENPrEVN1tjYNN9D/bxPLZO7SOCafw/Cg0a22V4owllMYBL/18deU/WjX+CHcHgs8E0jr7F3wTWC14HAn/R8VrTxvIQnS4kz2XSLH/4Zu0UsZdha3RxU82ynyKXN8G3G0RAkNnFR9ZSHXUABfiFyn7AuW8WHkPZB6ULkqU6wTrNDdi8osKJrHU6g1QV8aALvQ/exU36gYd1TK5fIRu6cJqb4sW+yedW94499NkXEjbVmG38=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
